package filetypes

var BranchMapping = map[string]string{
	"feature": ConventionalFeat,
	"bugfix":  ConventionalFix,
	"release": ConventionalChore,
	"hotfix":  ConventionalFix,
	"support": ConventionalFix,
}

var NameMapping = map[string]string{
	"requirements.txt":              ConventionalBuildDeps,
	"justfile":                      ConventionalBuild,
	"requirements-dev.txt":          ConventionalBuildDeps,
	"dev-requirements.txt":          ConventionalBuildDeps,
	"requirements-test.txt":         ConventionalBuildDeps,
	"test-requirements.txt":         ConventionalBuildDeps,
	"lazy-lock.json":                ConventionalBuildDeps,
	"selene.toml":                   ConventionalChore,
	"pipfile":                       ConventionalBuildDeps,
	"Pipefile.lock":                 ConventionalBuildDeps,
	"poetry.toml":                   ConventionalBuildDeps,
	"poetry.lock":                   ConventionalBuildDeps,
	"pyproject.toml":                ConventionalBuildDeps,
	"setup.py":                      ConventionalBuildDeps,
	"setup.cfg":                     ConventionalBuildDeps,
	"gemfile":                       ConventionalBuildDeps,
	"gemfile.lock":                  ConventionalBuildDeps,
	"package-lock.json":             ConventionalBuildDeps,
	"shrinkwrap.json":               ConventionalBuildDeps,
	"yarn.lock":                     ConventionalBuildDeps,
	"composer.json":                 ConventionalBuildDeps,
	"composer.lock":                 ConventionalBuildDeps,
	"go.mod":                        ConventionalBuildDeps,
	"go.sum":                        ConventionalBuildDeps,
	"cargo.toml":                    ConventionalBuildDeps,
	"cargo.lock":                    ConventionalBuildDeps,
	"deps.ts":                       ConventionalBuildDeps,
	"test_deps.ts":                  ConventionalBuildDeps,
	"dev_deps.ts":                   ConventionalBuildDeps,
	"import_map.json":               ConventionalBuildDeps,
	"license":                       ConventionalDocs,
	"license.txt":                   ConventionalDocs,
	"license.md":                    ConventionalDocs,
	".dockerignore":                 ConventionalBuild,
	"dockerfile":                    ConventionalBuild,
	"docker-compose.yml":            ConventionalBuild,
	"gnumakefile":                   ConventionalBuild,
	"makefile":                      ConventionalBuild,
	"rakefile":                      ConventionalBuild,
	"rakefile.rb":                   ConventionalBuild,
	"Rakefile.rb":                   ConventionalBuild,
	"package.json":                  ConventionalBuild,
	"gradlew":                       ConventionalBuild,
	"grailsw":                       ConventionalBuild,
	"micronaut-cli.yml":             ConventionalBuild,
	".gitignore":                    ConventionalChore,
	".editorconfig":                 ConventionalChore,
	".pylintrc":                     ConventionalChore,
	".isort.cfg":                    ConventionalChore,
	".flake8":                       ConventionalChore,
	"pytest.ini":                    ConventionalChore,
	".coveragerc":                   ConventionalChore,
	".npmignore":                    ConventionalChore,
	".npmrc":                        ConventionalChore,
	".babelrc":                      ConventionalChore,
	".eslintrc":                     ConventionalChore,
	".browserslistrc":               ConventionalChore,
	"browserslist":                  ConventionalChore,
	"rollup.config.js":              ConventionalChore,
	"webpack.config.js":             ConventionalChore,
	"npm-shrinkwrap.json":           ConventionalChore,
	"tsconfig.json":                 ConventionalChore,
	"tslint.json":                   ConventionalChore,
	".env":                          ConventionalChore,
	".env.dev":                      ConventionalChore,
	".env.prod":                     ConventionalChore,
	".env.template":                 ConventionalChore,
	".github/workflows":             ConventionalCI,
	".github/issuse_template":       ConventionalDocs,
	".github/pull_request_template": ConventionalDocs,
	"readme":                        ConventionalDocs,
	"readme.md":                     ConventionalDocs,
	"readme.txt":                    ConventionalDocs,
	"installation.md":               ConventionalDocs,
	"usage.md":                      ConventionalDocs,
	"development.md":                ConventionalDocs,
	"deploy.md":                     ConventionalDocs,
	"security.md":                   ConventionalDocs,
	"contributing.md":               ConventionalDocs,
	"changelog.md":                  ConventionalDocs,
	"attributions":                  ConventionalDocs,
	"releases.md":                   ConventionalDocs,
	"funding.md":                    ConventionalDocs,
	"pull_request_template.md":      ConventionalDocs,
	"issue_template.md":             ConventionalDocs,
	"code_of_conduct.md":            ConventionalDocs,
	"maintainers.txt":               ConventionalDocs,
	"codeowners":                    ConventionalDocs,
	"sample.png":                    ConventionalDocs,
	"sample-1.png":                  ConventionalDocs,
	"sample-2.png":                  ConventionalDocs,
	"screenshot.png":                ConventionalDocs,
	"preview.png":                   ConventionalDocs,
	".gitlab-ci.yml":                ConventionalCI,

	// directory Wildcards
	".github/*":   ConventionalDocs,
	".circleci/*": ConventionalCI,
	".cargo/*":    ConventionalBuildDeps,
	".vscode/*":   ConventionalChore,
	"docs/*":      ConventionalDocs,
	"test/*":      ConventionalTest,
	"tests/*":     ConventionalTest,
	"spec/*":      ConventionalTest,
	"__mocks__/*": ConventionalTest,
	"unit*":       ConventionalTest,

	// extension wildcards
	"*.md":        ConventionalDocs,
	"*_test.go":   ConventionalTest,
	"*.yml":       ConventionalChore,
	"*.yaml":      ConventionalChore,
	"*.json":      ConventionalChore,
	"*.toml":      ConventionalChore,
	"*.ini":       ConventionalChore,
	"*.cfg":       ConventionalChore,
	"*.config.js": ConventionalChore,
	"*.gemspec":   ConventionalBuild,
	"*.bat":       ConventionalBuild,
	"*.gradle":    ConventionalBuild,
}

// Conventional Commit categories
const (
	ConventionalDocs      = "docs"
	ConventionalBuild     = "build"
	ConventionalBuildDeps = "build(deps)"
	ConventionalCI        = "ci"
	ConventionalChore     = "chore"
	ConventionalTest      = "test"
	ConventionalFix       = "fix"
	ConventionalFeat      = "feat"
	ConventionalUnknown   = "unknown"
)
